version: "3.3"

services:
  db_primary:
    container_name: "primary"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=my-secret-passwd
      - POSTGRES_DB=tap_postgres_test
    volumes:
      -  ./db_setup/config/postgresql.conf:/etc/postgresql/postgresql.conf
      -  ./db_setup/init-replication-user.sql:/docker-entrypoint-initdb.d/init-replication-user.sql
    command: >
      postgres
      -c config_file=/etc/postgresql/postgresql.conf
      -c max_replication_slots=5
      -c max_wal_senders=5
